# Generated by Django 6.1 on 2026-09-01 17:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='limit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
